# Generated by Django 6.0.2 on 2026-03-03 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content_data',
            field=models.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='news',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='news',
            name='headline_image',
            field=models.ImageField(upload_to='news/'),
        ),
    ]
