# Generated by Django 6.0.2 on 2026-03-03 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_web', '0002_alter_news_content_data_alter_news_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='news',
            name='content_data',
        ),
        migrations.CreateModel(
            name='NewsContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text_content', models.TextField(blank=True, null=True)),
                ('image_content', models.ImageField(blank=True, null=True, upload_to='news_sub/')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='main_web.news')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
